#!/usr/bin/env php

#<?php

include "src/Dates/BirthDates.php";
$birthDate = "1984-05-29";
$days = new \Mamay\Dates\BirthDates($birthDate);

$totalDays = $days->calc();



echo "$birthDate : $totalDays\n";
