#!/usr/bin/env php

#<?php

require_once "vendor/autoload.php";
$birthDate = "1984-05-29";
$days = new \mamay\Dates\BirthDates($birthDate);

$totalDays = $days->calc();



echo "$birthDate : $totalDays\n";
