#!/usr/bin/env php

#<?php

echo "hello";

$birthDate = "1984-05-29";
$todayDate = date("Y-m-d");

$birthTime = strtotime($birthDate);
$todayTime = strtotime($todayDate);

$totalSecs = $todayTime - $birthTime;
$totalDays = floor($totalSecs/3600/24);

echo "$birthDate : $totalDays\n";
